//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileStoreBLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BinhLuan
    {
        public int maBL { get; set; }
        public string noidungBL { get; set; }
        public Nullable<int> maSP { get; set; }
    
        public virtual SanPham SanPham { get; set; }
    }
}
