//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileStoreBLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhachHang
    {
        public int maKH { get; set; }
        public string tenKH { get; set; }
        public Nullable<int> tuoiKH { get; set; }
        public string diachiKH { get; set; }
        public string dienthoaiKH { get; set; }
        public string mailKH { get; set; }
    }
}
