//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileStoreBLL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MOBILESTOREDBEntities : DbContext
    {
        public MOBILESTOREDBEntities()
            : base("name=MOBILESTOREDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<KhachHang> KhachHangs { get; set; }
        public DbSet<PhanQuyen> PhanQuyens { get; set; }
        public DbSet<SanPham> SanPhams { get; set; }
        public DbSet<BinhLuan> BinhLuans { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
