//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileStoreBLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhanQuyen
    {
        public int maPQ { get; set; }
        public string username { get; set; }
        public string pass { get; set; }
        public Nullable<int> phanquyen1 { get; set; }
    }
}
