//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileStoreBLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        public SanPham()
        {
            this.BinhLuans = new HashSet<BinhLuan>();
        }
    
        public int maSP { get; set; }
        public string tenSP { get; set; }
        public string hangSX { get; set; }
        public string giaSP { get; set; }
        public string thongtinSP { get; set; }
        public Nullable<int> tinhtrangSP { get; set; }
    
        public virtual ICollection<BinhLuan> BinhLuans { get; set; }
    }
}
